const $ = (id) => document.getElementById(id);
const data = (window.PARISI_DATA || PARISI_DATA || []).map((item, index) => ({...item, id:index, search:[item.code,item.description,item.barcode,item.location,item.shelf,item.category,item.stockingStatus,item.section].join(' ').toLowerCase()}));
let query = '', filter = 'all', view = 'cards', results = data.slice(0, 60), stream = null;
const LS_RECENT='parisi_recent_v2', LS_FAV='parisi_favorites_v2', LS_THEME='parisi_theme_v2';
const getLS=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
const setLS=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const fmt=(v)=> (v===undefined||v===null||String(v).trim()==='' ? '—' : String(v));
const hasStock=(v)=> !isNaN(parseFloat(v)) && parseFloat(v)>0;
function escapeHtml(s){return fmt(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
function highlight(text){let safe=escapeHtml(text); if(!query) return safe; const q=query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); return safe.replace(new RegExp(`(${q})`,'ig'),'<mark>$1</mark>');}
function toast(t){const el=$('toast'); el.textContent=t; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),1300)}
function copy(t){navigator.clipboard?.writeText(t||''); toast('Copied: '+fmt(t)); event?.stopPropagation?.();}
function isFav(code){return getLS(LS_FAV).includes(code)}
function toggleFav(code){let f=getLS(LS_FAV); f=f.includes(code)?f.filter(x=>x!==code):[code,...f].slice(0,80); setLS(LS_FAV,f); renderFavorites(); renderResults(); event?.stopPropagation?.();}
function addRecent(q){q=q.trim(); if(q.length<2) return; let r=getLS(LS_RECENT); r=[q,...r.filter(x=>x.toLowerCase()!==q.toLowerCase())].slice(0,10); setLS(LS_RECENT,r); renderRecent();}
function passesFilter(i){return filter==='all'||(filter==='withLocation'&&i.location)||(filter==='withoutLocation'&&!i.location)||(filter==='withShelf'&&i.shelf)||(filter==='withoutShelf'&&!i.shelf)||(filter==='inStock'&&hasStock(i.availableStock))||(filter==='discontinued'&&(i.stockingStatus||'').toLowerCase().includes('discontinued'));}
function search(){const q=query.toLowerCase().trim(); let arr=data.filter(p=>passesFilter(p)); if(q){arr=arr.map(p=>{let score=0; if(p.code.toLowerCase()===q)score+=120; if(p.code.toLowerCase().startsWith(q))score+=70; if(p.code.toLowerCase().includes(q))score+=45; if((p.barcode||'').toLowerCase().includes(q))score+=40; if((p.location||'').toLowerCase().includes(q))score+=35; if((p.shelf||'').toLowerCase().includes(q))score+=35; if((p.description||'').toLowerCase().includes(q))score+=25; if(p.search.includes(q))score+=10; return {...p,score}}).filter(p=>p.score>0).sort((a,b)=>b.score-a.score||a.code.localeCompare(b.code));}
else arr=arr.slice(0,80); results=arr.slice(0,300); renderResults();}
function stats(){const total=data.length, loc=data.filter(x=>x.location).length, shelf=data.filter(x=>x.shelf).length, stock=data.filter(x=>hasStock(x.availableStock)).length, disc=data.filter(x=>(x.stockingStatus||'').toLowerCase().includes('discontinued')).length; const score=Math.round(((loc/total)+(shelf/total))/2*100); $('healthScore').textContent=score+'%'; $('stats').innerHTML=[['Total Products',total],['Location OK',loc],['No Location',total-loc],['Shelf OK',shelf],['In Stock',stock]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1].toLocaleString()}</strong></div>`).join(''); $('warningList').innerHTML=`<div class="warning"><b>${(total-loc).toLocaleString()}</b> products need location review.</div><div class="warning"><b>${(total-shelf).toLocaleString()}</b> products have no shelf assigned.</div><div class="warning"><b>${disc.toLocaleString()}</b> products marked discontinued.</div>`}
function card(p){const loc=p.location, shelf=p.shelf; return `<article class="card" onclick="openDetail(${p.id})"><div class="card-top"><div><div class="code">${highlight(p.code)}</div><p class="desc">${highlight(p.description||p.category||'No description available')}</p></div><button class="fav" onclick="toggleFav('${p.code.replace(/'/g,"\\'")}')">${isFav(p.code)?'★':'☆'}</button></div><div class="locrow"><div class="locbox"><span>Location</span><strong class="${loc?'ok':'bad'}">${highlight(loc||'NO LOCATION')}</strong></div><div class="locbox"><span>Shelf</span><strong class="${shelf?'ok':'bad'}">${highlight(shelf||'NO SHELF')}</strong></div></div><div class="meta"><span class="badge ${loc?'ok':'bad'}">${loc?'LOCATION OK':'NO LOCATION'}</span><span class="badge ${shelf?'ok':'bad'}">${shelf?'SHELF OK':'NO SHELF'}</span><span class="badge">Stock: ${fmt(p.availableStock)}</span><span class="badge">${escapeHtml(p.category||'No category')}</span></div><div class="copybar"><button onclick="copy('${p.code.replace(/'/g,"\\'")}')">Copy Code</button><button onclick="copy('${(loc||'').replace(/'/g,"\\'")}')">Copy Loc</button><button onclick="copy('${(shelf||'').replace(/'/g,"\\'")}')">Copy Shelf</button></div></article>`}
function renderResults(){const title=query?`Results for “${query}”`:'Search results'; $('resultsTitle').textContent=title; $('resultsMeta').textContent=`${results.length.toLocaleString()} result(s) shown ${results.length===300?'(top 300)':''}`; if(view==='cards'){$('results').classList.remove('hidden');$('tableWrap').classList.add('hidden');$('results').innerHTML=results.length?results.map(card).join(''):`<div class="empty"><h3>No product found</h3><p>Try a shorter code, barcode, location or shelf.</p></div>`}else{$('results').classList.add('hidden');$('tableWrap').classList.remove('hidden');$('tableBody').innerHTML=results.map(p=>`<tr onclick="openDetail(${p.id})"><td><b>${highlight(p.code)}</b></td><td>${highlight(p.description)}</td><td>${highlight(p.location||'—')}</td><td>${highlight(p.shelf||'—')}</td><td>${fmt(p.availableStock)}</td><td>${highlight(p.barcode||'—')}</td><td>${escapeHtml(p.stockingStatus||p.shelfStatus||'—')}</td></tr>`).join('')}}
function renderRecent(){const r=getLS(LS_RECENT); $('recentList').innerHTML=r.length?r.map(x=>`<button class="tag" onclick="setQuery('${x.replace(/'/g,"\\'")}')">${escapeHtml(x)}</button>`).join(''):'No recent searches yet.'}
function renderFavorites(){const f=getLS(LS_FAV); const favs=f.map(c=>data.find(p=>p.code===c)).filter(Boolean); $('favList').innerHTML=favs.length?favs.slice(0,20).map(p=>`<button class="tag" onclick="setQuery('${p.code.replace(/'/g,"\\'")}')">★ ${escapeHtml(p.code)}</button>`).join(''):'No favorites saved yet.'}
function setQuery(q){$('searchInput').value=q; query=q; addRecent(q); search();}
function openDetail(id){const p=data.find(x=>x.id===id); if(!p)return; const shelves=(p.allShelves||[]).map(s=>`<div class="field"><span>Shelf record</span><strong>${escapeHtml(s.shelf)} • Qty ${escapeHtml(s.qty||'—')} • ${escapeHtml(s.section||'—')}</strong></div>`).join(''); $('detail').innerHTML=`<p class="kicker">Product Details</p><h2>${escapeHtml(p.code)}</h2><p class="sub">${escapeHtml(p.description||'No description available')}</p><div class="locrow"><div class="locbox"><span>Location</span><strong class="${p.location?'ok':'bad'}">${escapeHtml(p.location||'NO LOCATION')}</strong></div><div class="locbox"><span>Shelf</span><strong class="${p.shelf?'ok':'bad'}">${escapeHtml(p.shelf||'NO SHELF')}</strong></div></div><div class="detail-grid">${[['Barcode',p.barcode],['Available Stock',p.availableStock],['Stocking Status',p.stockingStatus],['Category',p.category],['Kit Components',p.kitComponents],['Shelf Qty',p.shelfQty],['Section',p.section],['Shelf Status',p.shelfStatus],['Street',p.street],['Building',p.building],['Level',p.level],['Side',p.side],['Observation',p.obs]].map(([k,v])=>`<div class="field"><span>${k}</span><strong>${escapeHtml(v)}</strong></div>`).join('')}${shelves}</div><div class="copybar"><button onclick="copy('${p.code.replace(/'/g,"\\'")}')">Copy Code</button><button onclick="copy('${(p.location||'').replace(/'/g,"\\'")}')">Copy Location</button><button onclick="copy('${(p.shelf||'').replace(/'/g,"\\'")}')">Copy Shelf</button></div>`; $('detailDialog').showModal();}
function exportCSV(){const headers=['code','description','location','shelf','barcode','availableStock','stockingStatus','category','section','shelfQty']; const csv=[headers.join(',')].concat(results.map(r=>headers.map(h=>`"${String(r[h]||'').replace(/"/g,'""')}"`).join(','))).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='parisi_filtered_results.csv'; a.click();}
async function startScanner(){const box=$('scanner'), video=$('video'); box.classList.remove('hidden'); try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}}); video.srcObject=stream; await video.play(); if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['ean_13','ean_8','code_128','code_39','qr_code']}); const tick=async()=>{if(!stream)return; try{const codes=await detector.detect(video); if(codes.length){setQuery(codes[0].rawValue); stopScanner(); toast('Barcode found')}}catch(e){} requestAnimationFrame(tick)}; tick();}else toast('Camera open. BarcodeDetector not supported here.')}catch(e){toast('Camera blocked or unavailable')}}
function stopScanner(){if(stream){stream.getTracks().forEach(t=>t.stop()); stream=null} $('scanner').classList.add('hidden')}
$('searchInput').addEventListener('input',e=>{query=e.target.value.trim(); if(query.length>1)addRecent(query); search();}); $('clearSearch').onclick=()=>setQuery(''); document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active')); b.classList.add('active'); filter=b.dataset.filter; search();}); $('cardsView').onclick=()=>{view='cards';$('cardsView').classList.add('active');$('tableViewBtn').classList.remove('active');renderResults()}; $('tableViewBtn').onclick=()=>{view='table';$('tableViewBtn').classList.add('active');$('cardsView').classList.remove('active');renderResults()}; $('exportBtn').onclick=exportCSV; $('closeDialog').onclick=()=>$('detailDialog').close(); $('clearRecent').onclick=()=>{setLS(LS_RECENT,[]);renderRecent()}; $('clearFavs').onclick=()=>{setLS(LS_FAV,[]);renderFavorites();renderResults()}; $('scanBtn').onclick=startScanner; $('stopScan').onclick=stopScanner; $('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem(LS_THEME,document.body.classList.contains('light')?'light':'dark')}; if(localStorage.getItem(LS_THEME)==='light')document.body.classList.add('light'); document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('searchInput').focus()} if(e.key==='Escape')stopScanner()});
stats(); renderRecent(); renderFavorites(); search();
